# -*- coding: utf-8 -*-
"""Week9D2XP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eON_AwSiz4vzI9bu6kuw1o_wXxfb7Lg0
"""

#Comprehensive Course on Advanced Data Visualization Techniques and SQLAlchemy
#Exercise 1

### download and extract chinook sample DB
import urllib.request
import zipfile
from functools import partial
import os
import sqlalchemy

chinook_url = 'http://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip'
if not os.path.exists('chinook.zip'):
    print('downloading chinook.zip ', end='')
    with urllib.request.urlopen(chinook_url) as response:
        with open('chinook.zip', 'wb') as f:
            for data in iter(partial(response.read, 4*1024), b''):
                print('.', end='', flush=True)
                f.write(data)

zipfile.ZipFile('chinook.zip').extractall()
assert os.path.exists('chinook.db')

### open the database using sqlalchemy module interface
engine = sqlalchemy.create_engine('sqlite:///chinook.db')
cur = engine.connect()


### useful: functions for displaying results from sql queries using pandas
from IPython.display import display
import pandas as pd

def sql(query):
    print()
    print(query)
    print()

def get_results(query):
    global engine
    q = query.statement if isinstance(query, sqlalchemy.orm.query.Query) else query
    return pd.read_sql(q, engine)

def display_results(query):
    df = get_results(query)
    display(df)
    sql(query)

### useful: extract classes from the chinook database
metadata = sqlalchemy.MetaData()
metadata.reflect(engine)

## we need to do this once
from sqlalchemy.ext.automap import automap_base

# produce a set of mappings from this MetaData.
Base = automap_base(metadata=metadata)

# calling prepare() just sets up mapped classes and relationships.
Base.prepare()

# also prepare an orm session
from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
session = Session()

inspector = sqlalchemy.inspect(engine)
table_names = inspector.get_table_names()
print("Tables in the database:")
for table_name in table_names:
    print(table_name)

query = "SELECT * FROM tracks LIMIT 3;"
display_results(query)

query = """
SELECT
    t.Name AS TrackName,
    a.Title AS AlbumTitle
FROM
    tracks AS t
JOIN
    albums AS a ON t.AlbumId = a.AlbumId
LIMIT 20;
"""
display_results(query)

query = """
SELECT
    t.Name AS TrackName,
    SUM(ii.Quantity) AS TotalQuantitySold
FROM
    invoice_items AS ii
JOIN
    tracks AS t ON ii.TrackId = t.TrackId
GROUP BY
    t.Name
ORDER BY
    TotalQuantitySold DESC
LIMIT 10;
"""
display_results(query)

query = """
SELECT
    t.Name AS TrackName,
    ii.Quantity
FROM
    invoice_items AS ii
JOIN
    tracks AS t ON ii.TrackId = t.TrackId
LIMIT 10;
"""
display_results(query)

query = """
SELECT
    ar.Name AS ArtistName,
    SUM(ii.Quantity) AS TotalQuantitySold
FROM
    artists AS ar
JOIN
    albums AS al ON ar.ArtistId = al.ArtistId
JOIN
    tracks AS t ON al.AlbumId = t.AlbumId
JOIN
    invoice_items AS ii ON t.TrackId = ii.TrackId
GROUP BY
    ar.Name
ORDER BY
    TotalQuantitySold DESC
LIMIT 10;
"""
display_results(query)